version: "3.8"

services:
  spam-classifier:
    image: nitinjmv/spam-classifier:latest
    ports:
      - "80:5000"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
