# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: spam-classifier
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: spam-classifier
#   template:
#     metadata:
#       labels:
#         app: spam-classifier
#     spec:
#       containers:
#       - name: spam-classifier
#         image: nitinjmv/spam-classifier-app:latest
#         ports:
#         - containerPort: 5000


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spam-classifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spam-classifier
  template:
    metadata:
      labels:
        app: spam-classifier
    spec:
      containers:
        - name: spam-classifier
          image: nitinjmv/spam-classifier-app:latest
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: spam-classifier-service
spec:
  selector:
    app: spam-classifier
  ports:
    - port: 80
      targetPort: 5000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spam-classifier-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: spam.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spam-classifier-service
                port:
                  number: 80
