apiVersion: apps/v1
kind: Deployment
metadata:
  name: spam-classifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spam-classifier
  template:
    metadata:
      labels:
        app: spam-classifier
    spec:
      containers:
      - name: spam-classifier
        image: nitinjmv/spam-classifier-app:latest
        ports:
        - containerPort: 5000
