# apiVersion: v1
# kind: Service
# metadata:
#   name: spam-classifier-service
# spec:
#   type: NodePort
#   selector:
#     app: spam-classifier
#   ports:
#   - port: 80
#     targetPort: 5000
#     nodePort: 30080

apiVersion: v1
kind: Service
metadata:
  name: spam-classifier-service
spec:
  type: LoadBalancer
  selector:
    app: spam-classifier
  ports:
    - port: 80
      targetPort: 5000
