# apiVersion: v1
# kind: Service
# metadata:
#   name: spam-classifier-service
# spec:
#   type: NodePort
#   selector:
#     app: spam-classifier
#   ports:
#   - port: 80
#     targetPort: 5000
#     nodePort: 30080

# apiVersion: v1
# kind: Service
# metadata:
#   name: spam-classifier-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: spam-classifier
#   ports:
#     - port: 80
#       targetPort: 5000

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spam-classifier-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: spam.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spam-classifier-service
                port:
                  number: 80

