name: Continuous Deployment Pipeline

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "Run id of the model to promote and deploy"
        required: false

jobs:
  build-docker:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: https://dagshub.com/nitinjmv/mlops-pipeline.mlflow
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      GH_PAT_TOKEN: ${{ secrets.GH_PAT }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          pip install mlflow joblib scikit-learn pandas flask nltk
      - name: Promote model for deployment
        run: PYTHONPATH=. python src/utils/promote_model.py ${{github.event.inputs.run_id}}
      - name: Build Docker image
        run: docker build --no-cache -t spam-classifier-app:latest .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to DockerHub
        run: |
          echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin
          docker tag spam-classifier-app nitinjmv/spam-classifier-app:latest
          docker push nitinjmv/spam-classifier-app:latest

      - name: Set up GCP credentials
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}" | base64 -d > /tmp/gcp-key.json
          cat /tmp/gcp-key.json | jq .  # validate
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json

      - name: Deploy to Minikube
        run: |
          script:
          - echo "Deploying to Minikube on GCP VM..."
          - 'ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY user@<GCP_VM_IP> << ''EOF''

            kubectl apply -f deployment/deployment.yaml
            kubectl apply -f deployment/service.yaml
            kubectl rollout status deployment/my-app

            EOF'
          only:
          - main
