name: Continuous Deployment Pipeline

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "Run id of the model to promote and deploy"
        required: false

jobs:
  docker-build:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: https://dagshub.com/nitinjmv/mlops-pipeline.mlflow
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      GH_PAT_TOKEN: ${{ secrets.GH_PAT }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          pip install mlflow joblib scikit-learn pandas flask nltk
      - name: Promote model for deployment
        run: PYTHONPATH=. python src/utils/promote_model.py ${{github.event.inputs.run_id}}
      - name: Build Docker image
        run: docker build --no-cache -t spam-classifier-app:latest .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to DockerHub
        run: |
          echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin
          docker tag spam-classifier-app nitinjmv/spam-classifier-app:latest
          docker push nitinjmv/spam-classifier-app:latest

  deploy-to-minikube:
    name: Deploy to Minikube (Self-Hosted)
    runs-on: [self-hosted, minikube-runner]
    needs: docker-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f https://raw.githubusercontent.com/nitinjmv/mlops-pipeline/refs/heads/main/k8s/service.yml
          kubectl apply -f https://raw.githubusercontent.com/nitinjmv/mlops-pipeline/refs/heads/main/k8s/deployment.yml
