name: Deployment application

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "Run id of the model to promote and deploy"
        required: false

jobs:
  build-docker:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: https://dagshub.com/nitinjmv/mlops-pipeline.mlflow
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      GH_PAT_TOKEN: ${{ secrets.GH_PAT }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          pip install mlflow joblib scikit-learn pandas flask nltk

      - name: Promote model for deployment
        run: PYTHONPATH=. python src/utils/promote_model.py ${{github.event.inputs.run_id}}
      - name: Build Docker image
        run: docker build -t spam-classifier-app .

      # Optional: Push to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker tag spam-api ${{ secrets.DOCKER_USERNAME }}/spam-api:latest && docker push ${{ secrets.DOCKER_USERNAME }}/spam-api:latest
