name: Preprocess, Train, Test, Validate

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/ci-cd.yml"

jobs:
  build-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: data ingestion
        run: PYTHONPATH=. python src/data_pipeline/data_ingestion.py

      - name: data preprocessing
        run: PYTHONPATH=. python src/data_pipeline/data_preprocessing.py

      - name: feature_engineering
        run: PYTHONPATH=. python src/data_pipeline/feature_engineering.py

      - name: Initialize DVC with Git context
        run: |
          git config --global user.name "nitinjmv"
          git config --global user.email "nitinjmv@github.com"
          dvc init
          git add .dvc .dvcignore
          git commit -m "Initialize DVC"

      - name: Track DVC Outputs
        run: |
          dvc add data/raw/train.csv data/raw/test.csv
          dvc add data/interim/test_processed.csv data/interim/train_processed.csv
          dvc add data/processed/test_tfidf.csv data/processed/train_tfidf.csv
          git add data/raw/train.csv.dvc data/raw/test.csv.dvc
          git add data/interim/test_processed.csv.dvc data/interim/train_processed.csv.dvc
          git add data/processed/test_tfidf.csv.dvc data/processed/train_tfidf.csv.dvc
          git commit -m "Auto DVC update"
          dvc push

      - name: Run Tests
        run: |
          PYTHONPATH=. pytest src/data_pipeline/test_data_ingestion.py
          PYTHONPATH=. pytest src/data_pipeline/test_data_preprocessing.py

      - name: model building
        run: PYTHONPATH=. python src/model_pipeline/model_building.py

      - name: model evaluation
        run: PYTHONPATH=. python src/model_pipeline/model_evaluation.py

      - name: Start Flask App
        run: |
          nohup python app/app.py &
